version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - npm ci
      - npm run build || true
      - docker build -t monitoramento-web-agent:latest .
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'